// ══════════════════════════════════════════════════════
//  DATA
// ══════════════════════════════════════════════════════

const lignesLouage = {
  "Tunis": {
    "Sousse":    { prix: 13.5,  temps: "2h00",  station: "Moncef Bey" },
    "Monastir":  { prix: 14.85, temps: "2h30",  station: "Moncef Bey" },
    "Kairouan":  { prix: 14.6,  temps: "2h45",  station: "Moncef Bey" },
    "Mahdia":    { prix: 17.65, temps: "3h15",  station: "Moncef Bey" },
    "Sfax":      { prix: 22.75, temps: "3h30",  station: "Moncef Bey" },
    "Bizerte":   { prix: 6.5,   temps: "1h10",  station: "Bab Saadoun" },
    "Nabeul":    { prix: 4.7,   temps: "1h10",  station: "Bab Alioua" },
    "Hammamet":  { prix: 6.8,   temps: "1h20",  station: "Bab Alioua" },
    "Zaghouan":  { prix: 5.35,  temps: "1h15",  station: "Bab Alioua" },
    "Le Kef":    { prix: 15.0,  temps: "3h00",  station: "Bab Saadoun" },
    "Jendouba":  { prix: 14.5,  temps: "3h20",  station: "Bab Saadoun" },
    "Tabarka":   { prix: 15.0,  temps: "4h00",  station: "Bab Saadoun" },
    "Ras Jebel": { prix: 5.7,   temps: "1h15",  station: "Bab Saadoun" },
    "Béja":      { prix: 9.5,   temps: "1h45",  station: "Bab Saadoun" },
    "Kélibia":   { prix: 8.8,   temps: "1h40",  station: "Bab Alioua" },
    "Gabès":     { prix: 32.0,  temps: "5h00",  station: "Moncef Bey" },
    "Gafsa":     { prix: 27.0,  temps: "4h30",  station: "Moncef Bey" },
    "Tozeur":    { prix: 34.0,  temps: "6h00",  station: "Moncef Bey" },
  },
  "Sousse": {
    "Tunis":     { prix: 13.5,  temps: "2h00",  station: "Station Sousse Nord" },
    "Monastir":  { prix: 2.4,   temps: "0h40",  station: "Station Sousse" },
    "Kairouan":  { prix: 6.2,   temps: "1h15",  station: "Station Sousse" },
    "Sfax":      { prix: 12.4,  temps: "1h45",  station: "Station Sousse" },
    "Gabès":     { prix: 22.3,  temps: "3h15",  station: "Station Sousse" },
    "Le Kef":    { prix: 19.0,  temps: "3h30",  station: "Station Sousse" },
    "Jendouba":  { prix: 21.0,  temps: "3h50",  station: "Station Sousse" },
    "El Jem":    { prix: 8.6,   temps: "1h15",  station: "Station Sousse" },
    "Mahdia":    { prix: 5.9,   temps: "1h05",  station: "Station Sousse" },
    "Nabeul":    { prix: 8.3,   temps: "1h15",  station: "Station Sousse" },
    "Hammamet":  { prix: 7.5,   temps: "1h00",  station: "Station Sousse" },
    "Béja":      { prix: 18.0,  temps: "3h00",  station: "Station Sousse" },
    "Bizerte":   { prix: 19.0,  temps: "3h10",  station: "Station Sousse" },
  },
  "Nabeul": {
    "Tunis":     { prix: 6.6,   temps: "1h20",  station: "Station Nabeul" },
    "Kairouan":  { prix: 10.6,  temps: "2h05",  station: "Station Nabeul" },
    "Monastir":  { prix: 10.9,  temps: "2h00",  station: "Station Nabeul" },
    "Zaghouan":  { prix: 6.5,   temps: "1h20",  station: "Station Nabeul" },
    "Sousse":    { prix: 8.3,   temps: "1h15",  station: "Station Nabeul" },
    "Kélibia":   { prix: 5.35,  temps: "0h55",  station: "Station Nabeul" },
    "Hammamet":  { prix: 2.0,   temps: "0h25",  station: "Station Nabeul" },
  },
  "Sfax": {
    "Tunis":     { prix: 22.75, temps: "3h30",  station: "Station Sfax" },
    "Sousse":    { prix: 12.4,  temps: "1h45",  station: "Station Sfax" },
    "Gabès":     { prix: 9.0,   temps: "2h00",  station: "Station Sfax" },
    "Kébili":    { prix: 21.0,  temps: "3h30",  station: "Station Sfax" },
    "Gafsa":     { prix: 14.0,  temps: "2h30",  station: "Station Sfax" },
    "Mahdia":    { prix: 10.0,  temps: "1h30",  station: "Station Sfax" },
    "El Jem":    { prix: 6.0,   temps: "0h55",  station: "Station Sfax" },
    "Monastir":  { prix: 14.0,  temps: "2h10",  station: "Station Sfax" },
  },
  "Gabès": {
    "Sfax":      { prix: 9.0,   temps: "2h00",  station: "Station Gabès" },
    "Djerba":    { prix: 14.55, temps: "2h30",  station: "Station Gabès" },
    "Sousse":    { prix: 22.3,  temps: "3h15",  station: "Station Gabès" },
    "Tozeur":    { prix: 17.6,  temps: "4h30",  station: "Station Gabès" },
    "Médenine":  { prix: 8.0,   temps: "1h30",  station: "Station Gabès" },
    "Tunis":     { prix: 32.0,  temps: "5h00",  station: "Station Gabès" },
  },
  "Monastir": {
    "Sousse":    { prix: 2.4,   temps: "0h40",  station: "Station Monastir" },
    "Kairouan":  { prix: 7.95,  temps: "1h15",  station: "Station Monastir" },
    "Tunis":     { prix: 14.85, temps: "2h30",  station: "Station Monastir" },
    "Sfax":      { prix: 14.0,  temps: "2h10",  station: "Station Monastir" },
    "Mahdia":    { prix: 4.5,   temps: "0h50",  station: "Station Monastir" },
    "Nabeul":    { prix: 10.9,  temps: "2h00",  station: "Station Monastir" },
  },
  "Kairouan": {
    "Monastir":  { prix: 7.95,  temps: "1h15",  station: "Station Kairouan" },
    "Sousse":    { prix: 6.2,   temps: "1h15",  station: "Station Kairouan" },
    "Tunis":     { prix: 14.6,  temps: "2h45",  station: "Station Kairouan" },
    "Sfax":      { prix: 12.0,  temps: "2h00",  station: "Station Kairouan" },
    "Nabeul":    { prix: 10.6,  temps: "2h05",  station: "Station Kairouan" },
    "Le Kef":    { prix: 16.0,  temps: "2h30",  station: "Station Kairouan" },
  },
  "Bizerte": {
    "Tunis":     { prix: 6.5,   temps: "1h10",  station: "Station Bizerte" },
    "Béja":      { prix: 9.25,  temps: "1h35",  station: "Station Bizerte" },
  },
  "Béja": {
    "Tabarka":   { prix: 6.5,   temps: "2h10",  station: "Station Béja" },
    "Tunis":     { prix: 9.5,   temps: "1h45",  station: "Station Béja" },
    "Bizerte":   { prix: 9.25,  temps: "1h35",  station: "Station Béja" },
    "Jendouba":  { prix: 4.5,   temps: "0h45",  station: "Station Béja" },
  },
  "Jendouba": {
    "Tunis":     { prix: 14.5,  temps: "3h20",  station: "Station Jendouba" },
    "Béja":      { prix: 4.5,   temps: "0h45",  station: "Station Jendouba" },
    "Tabarka":   { prix: 5.0,   temps: "1h10",  station: "Station Jendouba" },
    "Bousalem":  { prix: 1.8,   temps: "0h20",  station: "Station Jendouba" },
  },
  "Le Kef": {
    "Kasserine": { prix: 11.5,  temps: "1h40",  station: "Station Le Kef" },
    "Tunis":     { prix: 15.0,  temps: "3h00",  station: "Station Le Kef" },
    "Sousse":    { prix: 19.0,  temps: "3h30",  station: "Station Le Kef" },
    "Kairouan":  { prix: 16.0,  temps: "2h30",  station: "Station Le Kef" },
  },
  "Mahdia": {
    "Sousse":    { prix: 5.9,   temps: "1h05",  station: "Station Mahdia" },
    "El Jem":    { prix: 8.0,   temps: "1h10",  station: "Station Mahdia" },
    "Tunis":     { prix: 17.65, temps: "3h15",  station: "Station Mahdia" },
    "Monastir":  { prix: 4.5,   temps: "0h50",  station: "Station Mahdia" },
    "Sfax":      { prix: 10.0,  temps: "1h30",  station: "Station Mahdia" },
  },
  "Gafsa": {
    "Tunis":     { prix: 27.0,  temps: "4h30",  station: "Station Gafsa" },
    "Sfax":      { prix: 14.0,  temps: "2h30",  station: "Station Gafsa" },
    "Tozeur":    { prix: 8.0,   temps: "1h30",  station: "Station Gafsa" },
    "Kébili":    { prix: 10.0,  temps: "1h45",  station: "Station Gafsa" },
    "Kasserine": { prix: 7.0,   temps: "1h20",  station: "Station Gafsa" },
  },
  "Tozeur": {
    "Gafsa":     { prix: 8.0,   temps: "1h30",  station: "Station Tozeur" },
    "Gabès":     { prix: 17.6,  temps: "4h30",  station: "Station Tozeur" },
    "Kébili":    { prix: 12.0,  temps: "2h00",  station: "Station Tozeur" },
  },
  "Kébili": {
    "Sfax":      { prix: 21.0,  temps: "3h30",  station: "Station Kébili" },
    "Gafsa":     { prix: 10.0,  temps: "1h45",  station: "Station Kébili" },
    "Tozeur":    { prix: 12.0,  temps: "2h00",  station: "Station Kébili" },
  },
  "Médenine": {
    "Gabès":     { prix: 8.0,   temps: "1h30",  station: "Station Médenine" },
    "Djerba":    { prix: 6.5,   temps: "1h00",  station: "Station Médenine" },
    "Tataouine": { prix: 7.0,   temps: "1h15",  station: "Station Médenine" },
    "Sfax":      { prix: 17.0,  temps: "3h00",  station: "Station Médenine" },
  },
  "Kasserine": {
    "Le Kef":    { prix: 11.5,  temps: "1h40",  station: "Station Kasserine" },
    "Gafsa":     { prix: 7.0,   temps: "1h20",  station: "Station Kasserine" },
    "Sousse":    { prix: 18.0,  temps: "2h45",  station: "Station Kasserine" },
  },
  "Zaghouan": {
    "Tunis":     { prix: 5.35,  temps: "1h15",  station: "Station Zaghouan" },
    "Nabeul":    { prix: 6.5,   temps: "1h20",  station: "Station Zaghouan" },
    "Sousse":    { prix: 10.0,  temps: "2h00",  station: "Station Zaghouan" },
  },
  "Hammamet": {
    "Tunis":     { prix: 6.8,   temps: "1h20",  station: "Station Hammamet" },
    "Nabeul":    { prix: 2.0,   temps: "0h25",  station: "Station Hammamet" },
    "Sousse":    { prix: 7.5,   temps: "1h00",  station: "Station Hammamet" },
  },
  "El Jem": {
    "Sousse":    { prix: 8.6,   temps: "1h15",  station: "Station El Jem" },
    "Sfax":      { prix: 6.0,   temps: "0h55",  station: "Station El Jem" },
    "Mahdia":    { prix: 8.0,   temps: "1h10",  station: "Station El Jem" },
  },
};

const tarifsVerifies = [
  { trajet: "Tunis (Bab Saadoun) – Bizerte", prix: "6,500 DT", obs: "vérifié par Emily, fév. 2025" },
  { trajet: "Tunis (Bab Saadoun) – Jendouba", prix: "14.500 DT", obs: "vérifié par Krayem, oct. 2025" },
  { trajet: "Tunis (Bab Saadoun) – Tabarka", prix: "15 DT", obs: "vérifié par Spacho, sept. 2023" },
  { trajet: "Tunis (Bab Saadoun) – Le Kef", prix: "15 DT", obs: "vérifié par Yasser, oct. 2024" },
  { trajet: "Tunis (Bab Saadoun) – Ras Jebel", prix: "5.700 DT", obs: "vérifié par Krayem, oct. 2025" },
  { trajet: "Tunis (Bab Alioua) – Nabeul", prix: "4.700 DT", obs: "vérifié par Kaloun, jan. 2015" },
  { trajet: "Tunis (Bab Alioua) – Korba", prix: "6.800 DT", obs: "vérifié par Laurent, juil. 2023" },
  { trajet: "Tunis (Bab Alioua) – Kélibia", prix: "8.800 DT", obs: "vérifié par Aziz, août 2022" },
  { trajet: "Tunis (Bab Alioua) – Hammamet Nord", prix: "6.800 DT", obs: "vérifié par Emily, fév. 2025" },
  { trajet: "Tunis (Bab Alioua) – Zaghouan", prix: "5.350 DT", obs: "vérifié par Mara, juil. 2025" },
  { trajet: "Tunis (Moncef Bey) – Sousse", prix: "13.500 DT", obs: "vérifié par Mélanie, oct. 2024" },
  { trajet: "Tunis (Moncef Bey) – Monastir", prix: "14.850 DT", obs: "vérifié par Emily, fév. 2025" },
  { trajet: "Tunis (Moncef Bey) – Kairouan", prix: "14.600 DT", obs: "vérifié par Boyang, déc. 2025" },
  { trajet: "Tunis (Moncef Bey) – Mahdia", prix: "17.650 DT", obs: "vérifié par Syrine, août 2024" },
  { trajet: "Nabeul – Tunis", prix: "6.600 DT", obs: "vérifié par Jérôme, oct. 2025" },
  { trajet: "Nabeul – Kélibia", prix: "5.350 DT", obs: "vérifié par Jérôme, oct. 2025" },
  { trajet: "Nabeul – Sousse", prix: "8.300 DT", obs: "vérifié par Hervé, sept. 2022" },
  { trajet: "Nabeul – Kairouan", prix: "10.600 DT", obs: "vérifié par Jérôme, oct. 2025" },
  { trajet: "Nabeul – Monastir", prix: "10.900 DT", obs: "vérifié par Jérôme, oct. 2025" },
  { trajet: "Sousse – Gabès", prix: "22.300 DT", obs: "vérifié par Franklin, oct. 2023" },
  { trajet: "Sousse – Tunis", prix: "13.500 DT", obs: "vérifié par Fafa, déc. 2025" },
  { trajet: "Sousse – Le Kef", prix: "19.000 DT", obs: "vérifié par Yasser, oct. 2024" },
  { trajet: "Sousse – Jendouba", prix: "21 DT", obs: "vérifié par Ahmed, juil. 2025" },
  { trajet: "Sousse – El Jem", prix: "8.600 DT", obs: "vérifié par Emilie, fév. 2025" },
  { trajet: "Sousse – Monastir", prix: "2.400 DT", obs: "vérifié par Boyang, déc. 2025" },
  { trajet: "Sousse – Mahdia", prix: "5.900 DT", obs: "vérifié par Claire, déc. 2024" },
  { trajet: "Sousse – Sfax", prix: "12.400 DT", obs: "vérifié par Emilie, fév. 2025" },
  { trajet: "Kairouan – Sousse", prix: "6.200 DT", obs: "vérifié par Boyang, déc. 2025" },
  { trajet: "Monastir – Kairouan", prix: "7.950 DT", obs: "vérifié par Emilie, fév. 2025" },
  { trajet: "Mahdia – El Jem", prix: "8.000 DT", obs: "vérifié par Blaise, avr. 2024" },
  { trajet: "Sfax – Tunis", prix: "22.750 DT", obs: "vérifié par Achraf, mars 2023" },
  { trajet: "Sfax – Kebili", prix: "21 DT", obs: "vérifié par Kaïs, jan. 2025" },
  { trajet: "Gabès – Sousse", prix: "22.300 DT", obs: "vérifié par Emilie, fév. 2025" },
  { trajet: "Gabès – Tozeur", prix: "17.600 DT", obs: "vérifié par Emily, fév. 2025" },
  { trajet: "Gabès – Djerba", prix: "14.550 DT", obs: "vérifié par Emily, fév. 2025" },
  { trajet: "Bizerte – Béja", prix: "9.250 DT", obs: "vérifié par Jean Jean, juil. 2025" },
  { trajet: "Béja – Tabarka", prix: "6.500 DT", obs: "vérifié par Jean Jean, juil. 2025" },
  { trajet: "Le Kef – Kasserine", prix: "11.500 DT", obs: "vérifié par Jean-Philippe, oct. 2023" },
  { trajet: "Jendouba – Bousalem", prix: "1.800 DT", obs: "vérifié par Aron, oct. 2023" },
];

const gouvernorats = [
  "Ariana","Béja","Ben Arous","Bizerte","Bousalem","Djerba","El Jem",
  "Gabès","Gafsa","Hammamet","Jendouba","Kairouan","Kasserine","Kébili",
  "Kélibia","Le Kef","Mahdia","La Manouba","Médenine","Monastir",
  "Nabeul","Sfax","Sidi Bouzid","Siliana","Sousse","Tabarka","Tataouine",
  "Tozeur","Tunis","Zaghouan"
];

const cityInfos = {
  "Ariana": { summary: "Proche de Tunis, Ariana est connue pour ses jardins, son lac et sa vie de quartier dynamique.", tags: ["Urbaine","Proche Tunis","Résidentielle"] },
  "Béja": { summary: "Ville du nord-ouest tunisien, capitale d'un riche gouvernorat agricole aux paysages vallonnés.", tags: ["Agriculture","Nature","Marché animé"] },
  "Ben Arous": { summary: "Zone urbaine et industrielle au sud de Tunis, avec un accès facile à la capitale.", tags: ["Industrielle","Urbaine","Proche Tunis"] },
  "Bizerte": { summary: "Grand port méditerranéen du nord tunisien, avec un vieux port charmant et de belles plages.", tags: ["Port","Plages","Histoire"] },
  "Bousalem": { summary: "Petite ville du nord-ouest sur la Medjerda, point de passage entre Jendouba et Béja.", tags: ["Rurale","Passage"] },
  "Djerba": { summary: "L'île de Djerba, joyau touristique du sud, est célèbre pour ses plages et son artisanat.", tags: ["Île","Tourisme","Plages"] },
  "El Jem": { summary: "Célèbre pour son amphithéâtre romain classé UNESCO, l'un des mieux conservés au monde.", tags: ["Patrimoine UNESCO","Histoire","Culture"] },
  "Gabès": { summary: "Ville du sud-est connue pour ses oasis côtières, ses marchés et la palmeraie qui borde la mer.", tags: ["Oasis","Côtière","Marchés"] },
  "Gafsa": { summary: "Cœur d'une région minière, Gafsa offre une expérience authentique du sud-ouest tunisien.", tags: ["Mines","Oasis","Authentique"] },
  "Hammamet": { summary: "Célèbre station balnéaire de la côte est, très fréquentée pour ses plages et ses hôtels.", tags: ["Balnéaire","Tourisme","Détente"] },
  "Jendouba": { summary: "Terre verte du nord-ouest, appréciée pour ses forêts de chênes-lièges et ses montagnes.", tags: ["Nature","Forêts","Montagnes"] },
  "Kairouan": { summary: "4ᵉ ville sainte de l'islam, Kairouan est réputée pour sa grande mosquée et son artisanat.", tags: ["Ville sainte","Histoire","Artisanat"] },
  "Kasserine": { summary: "Porte vers les montagnes de l'Atlas tunisien, avec la chaîne de Chaambi et ses forêts.", tags: ["Montagnes","Nature","Randonnée"] },
  "Kébili": { summary: "Centre du grand désert d'oasis du sud, idéal pour les excursions sahariennes.", tags: ["Désert","Oasis","Sahara"] },
  "Kélibia": { summary: "Belle ville côtière de la péninsule du Cap Bon, avec un fort byzantin et des eaux cristallines.", tags: ["Fort","Plages","Cap Bon"] },
  "Le Kef": { summary: "Ville historique du nord-ouest avec une imposante kasba et des panoramas sur la dorsale tunisienne.", tags: ["Kasba","Panorama","Histoire"] },
  "Mahdia": { summary: "Cité côtière fondée par les Fatimides, Mahdia allie plages de sable fin et médina authentique.", tags: ["Plages","Médina","Histoire"] },
  "La Manouba": { summary: "Gouvernorat résidentiel et universitaire au nord-ouest de Tunis.", tags: ["Universitaire","Résidentiel","Proche Tunis"] },
  "Médenine": { summary: "Point de départ pour Djerba et le désert, Médenine conserve les célèbres ksour berbères.", tags: ["Ksour berbères","Djerba","Désert"] },
  "Monastir": { summary: "Ville côtière historique avec son ribat, ses plages et une vie touristique animée toute l'année.", tags: ["Ribat","Plages","Tourisme"] },
  "Nabeul": { summary: "Capitale de la poterie tunisienne, Nabeul est réputée pour son marché du vendredi et ses plages.", tags: ["Artisanat","Plages","Marché"] },
  "Sfax": { summary: "Deuxième ville de Tunisie, grand port économique avec une médina historique très préservée.", tags: ["Économie","Port","Médina"] },
  "Sidi Bouzid": { summary: "Ville de l'intérieur, connue pour son agriculture et berceau de la révolution de 2010.", tags: ["Agriculture","Histoire récente","Intérieur"] },
  "Siliana": { summary: "Région de collines et de forêts du nord-ouest, idéale pour les amateurs de nature.", tags: ["Collines","Nature","Calme"] },
  "Sousse": { summary: "Troisième ville de Tunisie, Sousse est une station balnéaire avec une médina classée UNESCO.", tags: ["UNESCO","Plages","Tourisme"] },
  "Tabarka": { summary: "Perle du nord-ouest, Tabarka est célèbre pour son corail, ses plongées et son festival de jazz.", tags: ["Corail","Jazz","Plongée"] },
  "Tataouine": { summary: "Décors de Star Wars réels : les ksour et paysages rocheux du Sahara en font une destination unique.", tags: ["Star Wars","Ksour","Désert"] },
  "Tozeur": { summary: "Porte du Sahara tunisien, Tozeur éblouit avec ses palmeraies et son architecture en briques dorées.", tags: ["Palmeraies","Désert","Architecture"] },
  "Tunis": { summary: "La capitale tunisienne réunit médina historique, quartiers modernes et un réseau de transports centralisé.", tags: ["Capitale","Médina","Transports"] },
  "Zaghouan": { summary: "Ville des sources, Zaghouan est entourée de montagnes et abrite le célèbre temple des Eaux romain.", tags: ["Sources","Montagne","Antiquité"] },
};

const popularRoutes = [
  { from: "Tunis", to: "Sousse" },
  { from: "Tunis", to: "Sfax" },
  { from: "Sousse", to: "Monastir" },
  { from: "Tunis", to: "Bizerte" },
  { from: "Gabès", to: "Djerba" },
  { from: "Tunis", to: "Kairouan" },
];

// Map gov name in SVG -> display name
const svgToDisplay = {
  "La Manouba": "La Manouba", "Ben Arous": "Ben Arous",
};
